# Generated by Django 5.1.4 on 2025-01-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classroom',
            new_name='ClassLevel',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
