# Generated by Django 5.1.4 on 2025-01-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0003_teacher_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='classlevel',
            name='subject',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='classlevel',
            name='subject',
            field=models.ManyToManyField(related_name='classes', to='myapp.subject'),
        ),
    ]
