# Generated by Django 5.1.4 on 2025-01-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_roups_alter_attendance_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'teacher')], max_length=20),
        ),
    ]
